"""empty message

Revision ID: 4000318926f9
Revises: d4f7713e8252
Create Date: 2022-02-14 10:08:30.119347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4000318926f9'
down_revision = 'd4f7713e8252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
