"""empty message

Revision ID: d4f7713e8252
Revises: 83202c481799
Create Date: 2022-02-14 10:07:36.684729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f7713e8252'
down_revision = '83202c481799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tag')
    # ### end Alembic commands ###
